### ISSUE TITLE
ZoneController zones/{zoneid} always return HTTP 200 OK

### ISSUE THREAD

**Issue by Benczus** [ZsoltToth/ilona-measurement#15]
ZoneController zones/{zoneid} returns with an Unknown zone instead of exception. So the controller will always return with HTTP 200 OK. The problem may be caused by the exception handling in the  service implementation module.

It seems to be the service never throw ZoneNotFoundException. 

Test the case when the database is not available.

**Comment by ZsoltToth** [comment]
Is it done ?

**Comment by iasatan** [comment]
yes
